apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-master
  namespace: exercise-02
  labels:
    app: mariadb
    tier: backend
    role: master
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      tier: backend
      role: master
  template:
    metadata:
      labels:
        app: mariadb
        tier: backend
        role: master
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:latest
        ports:
          - name: mariadb-server
            containerPort: 3306
        resources:
          requests:
            cpu: "500m"
            memory: "500M"
          limits:
            cpu: "1"
            memory: "1G"
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: root-password
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-dbname
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-user
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-password
          - name: MARIADB_REPLICATION_MODE
            value: master
          - name: MARIADB_REPLICATION_USER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: repl-user
          - name: MARIADB_REPLICATION_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: repl-password
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 15
          periodSeconds: 5
