apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: exercise-01
  labels:
    app: mariadb
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      tier: backend
  template:
    metadata:
      labels: 
        app: mariadb
        tier: backend
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:latest
        env:
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: cm-exercise-01
              key: mariadb-databasename
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: cm-exercise-01
              key: mariadb-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password    
        ports:
        - name: mariadb-server
          containerPort: 3306