apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise-01
  labels:
    app: wordpress
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: bitnami/wordpress:4.9.7
        name: wordpress
        envFrom:
        - configMapRef:
            name: wordpress
        env:
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: database_name
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: database_user
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: database_password
        - name: WORDPRESS_EMAIL
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: wordpress_email
        ports:
        - name: wordpress
          containerPort: 80
        readinessProbe:
          tcpSocket:
            port: wordpress
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: wordpress
          initialDelaySeconds: 15
          periodSeconds: 20
